# config/packages/sonata_admin.yaml
sonata_admin:
  security:
    handler: sonata.admin.security.handler.role

    role_admin: ROLE_ADMIN
    role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]

sonata_user:
  security_acl: false
  manager_type: orm
  class:
    user: App\Application\Sonata\UserBundle\Entity\User
    group: App\Application\Sonata\UserBundle\Entity\Group

fos_user:
  db_driver: orm
  firewall_name:  admin
  user_class:     App\Application\Sonata\UserBundle\Entity\User

  group:
    group_class:   App\Application\Sonata\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

  service:
    user_manager: sonata.user.orm.user_manager

  from_email:
    address: "%env(MAIL_SENDER)%"
    sender_name: "%env(MAIL_USER)%"